#!/usr/bin/env python
"""
Unit test Convolution class.

Note
----
Use numpy.array_equal() to compare two arrays with integer elements.
Use numpy.allclose() to compare two arrays with floating-point number elements.

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""
import numba
import unittest
import numpy as np
from project.convolve import Convolve


class TestConvolve(unittest.TestCase):

    def test_convolve_2x2_with_2x2(self):
        """
        Test against 2x2 kernel resulting in 3x3 matrix
        """
        m = np.array([[1., 2.], [3., 4.]])
        k = np.array([[0.1, 0.2], [0.3, 0.4]])

        actual = Convolve.convolve2d(m, k)
        expected = np.array([[0.4, 1.1, 0.6], [1.4, 3.0, 1.4], [0.6, 1.1, 0.4]])

        result = np.allclose(actual, expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_2x2_with_3x3(self):
        """
        Test against 3x3 kernel resulting in 2x2 matrix
        """
        m = np.array([[1., 2.], [3., 4.]])
        k = np.array([[0.1, 0.2, 0.3],
                      [0.4, 0.5, 0.6],
                      [0.7, 0.8, 0.9]])

        actual = Convolve.convolve2d(m, k)
        expected = np.array([[1. * 0.5 + 2 * 0.6 + 0.8 * 3 + 0.9 * 4, 0.4 * 1 + 0.5 * 2 + 0.7 * 3 + 0.8 * 4],
                             [1 * 0.2 + 2 * 0.3 + 3 * 0.5 + 4 * 0.6, 1 * 0.1 + 2 * 0.2 + 3 * 0.4 + 4 * 0.5]])

        result = np.allclose(actual, expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_2x2_with_3x3_strides_2(self):
        """
        Test against 3x3 kernel resulting in 1x1 matrix with stride=2
        """
        m = np.array([[1., 2.], [3., 4.]])
        k = np.array([[0.1, 0.2, 0.3],
                      [0.4, 0.5, 0.6],
                      [0.7, 0.8, 0.9]])

        actual = Convolve.convolve2d(m, k, strides=(2, 2))
        expected = np.array([[1. * 0.5 + 2 * 0.6 + 0.8 * 3 + 0.9 * 4]])

        result = np.allclose(actual, expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_3x3_with_3x3_strides_2(self):
        """
        Test against 3x3 kernel resulting in 2x2 matrix with stride=2
        """
        m = np.array([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.]])
        k = np.array([[0.1, 0.2, 0.3],
                      [0.4, 0.5, 0.6],
                      [0.7, 0.8, 0.9]])

        actual = Convolve.convolve2d(m, k, strides=(2, 2))
        expected = np.array([[1 * 0.5 + 2 * 0.6 + 4 * 0.8 + 5 * 0.9, 2 * 0.4 + 3 * 0.5 + 5 * 0.7 + 6 * 0.8],
                             [4 * 0.2 + 5 * 0.3 + 7 * 0.5 + 8 * 0.6, 5 * 0.1 + 6 * 0.2 + 8 * 0.4 + 9 * 0.5]])

        result = np.allclose(actual, expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_64x64_with_3x3_strides_2(self):
        """
        Test 64x64 matrix against 3x3 kernel resulting in 32x32 matrix with stride=2
        """
        m = np.random.normal(size=(64, 64))
        k = np.random.normal(size=(3, 3))

        actual_out = Convolve.convolve2d(m, k, strides=(2, 2))

        actual = actual_out.shape
        expected = (32, 32)

        result = np.array_equal(actual, expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_size_2(self):
        """
        Test convolve layers.
        """
        m = np.ones((2, 2, 2))  # 2x2 matrix and 2 channels
        m[::, 1] = m[::, 1] * 2.0  # Second channel to all 2s.

        k = np.ones((3, 3, 2))  # 3x3 kernel and 2 channels

        actual = Convolve.convolve_tensor(m, k)

        self.assertTrue(actual.shape == (2, 2))

        actual = actual
        expected_0 = np.array([[4, 4], [4, 4]])
        expected_1 = np.array([[8, 8], [8, 8]])
        expected = expected_0 + expected_1
        result = np.array_equal(actual, expected_0 + expected_1)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_size_2_no_padding(self):
        """
        Test convolve layers.
        """
        m = np.ones((2, 2, 2))  # 2x2 matrix and 2 channels
        m[:, :, 1] = m[:, :, 1] * 2.0  # Second channel to all 2s.

        k = np.ones((2, 2, 2))  # 2x2 kernel and 2 channels

        actual = Convolve.convolve_tensor(m, k, use_padding=False)

        self.assertTrue(actual.shape == (1, 1))

        actual = actual
        expected_0 = np.array([[4]])
        expected_1 = np.array([[8]])
        expected = expected_0 + expected_1
        result = np.array_equal(actual, expected_0 + expected_1)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_output_8(self):
        """
        Test convolve layers.
        """
        m = np.ones((64, 64, 3))  # 3 layer 2x2 matrix
        m[:, :, 1] = m[:, :, 1] * 2.0  # Second channel to all 2s.
        k = np.ones((5, 5, 3, 8))  # 5x5 kernel with 3 channels, 8 output channels
        expected_output_shape = np.zeros((64, 64, 8)).shape

        actual = Convolve.convolve_tensor_multi_channel(m, k)

        # check shape
        self.assertTrue(actual.shape == expected_output_shape, "Unexpected shape")

    def test_convolve_tensor_output_8_no_padding(self):
        """
        Test convolve layers.
        """
        m = np.ones((64, 64, 3))  # 3 layer 2x2 matrix
        m[:, :, 1] = m[:, :, 1] * 2.0  # Second channel to all 2s.
        k = np.ones((5, 5, 3, 8))  # 5x5 kernel with 3 channels, 8 output channels
        expected_output_shape = np.zeros((60, 60, 8)).shape

        actual = Convolve.convolve_tensor_multi_channel(m, k, use_padding=False)

        # check shape
        self.assertTrue(actual.shape == expected_output_shape, "Unexpected shape")

    def test_convolve_tensor_8_channel_output_for_3_channel_input_training_set(self):
        """
        Test convolve layers.
        """
        training_set_size = 100

        m = np.ones((training_set_size, 64, 64, 3))  # 3 layer 64x64 matrix
        m[1] = m[1] * 2.0

        k = np.ones((3, 3, 3, 8))  # 3x3 kernel with 3 channels, 8 output channels

        expected = np.zeros((training_set_size, 64, 64, 8)).shape

        actual = Convolve.convolve_tensor_dataset_2(m, k)

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_2_channel_output_for_1_channel_input_training_set(self):
        """
        Test convolve layers.
        """
        training_set_size = 100

        m = np.ones((training_set_size, 64, 64, 1))  # 1 layer matrix
        k = np.ones((7, 7, 1, 5))  # 3x3 kernel with 3 channels, 5 output channels
        output = np.zeros((training_set_size, 64, 64, 5))
        expected = output.shape
        num_output_channels = k.shape[3]

        self.dataset = Convolve.convolve_tensor_dataset_2(m, k)
        actual = self.dataset

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_8_channel_output_for_3_channel_input_with_bias(self):
        """
        Test convolve layers.
        """
        training_set_size = 100

        m = np.ones((training_set_size, 64, 64, 3))  # 3 input channel 64x64 matrix

        k = np.ones((3, 3, 3, 8))  # 3x3 kernel, 3 input, 8 output channels
        bias = np.zeros((8))

        output = np.zeros((training_set_size, 64, 64, 8))
        expected = output.shape
        # num_output_channels = k.shape[0]

        for i in range(training_set_size):
            actual = Convolve.convolve_tensor_multi_channel(m[i, :], k, bias)
            output[i] = actual

        actual = output.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_8_channel_output_for_3_channel_input_training_set_with_bias(self):
        """
        Test convolve layers.
        """
        training_set_size = 100

        m = np.ones((training_set_size, 64, 64, 3))  # 3 input channel 64x64 matrix

        k = np.ones((3, 3, 3, 8))  # 3x3 kernel, 3 input, 8 output channels
        bias = np.zeros((8))

        output = np.zeros((training_set_size, 64, 64, 8))
        expected = output.shape
        # num_output_channels = k.shape[0]

        actual = Convolve.convolve_tensor_dataset_2(m, k, bias)

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_8_channel_output_for_3_channel_input_training_set_with_bias_strides_2(self):
        """
        Test convolve layers.
        """
        training_set_size = 5

        m = np.ones((training_set_size, 64, 64, 3))  # 3 input channel 64x64 matrix

        k = np.ones((5, 5, 3, 8))  # 3x3 kernel, 3 input, 8 output channels
        bias = np.zeros((8))

        expected = (training_set_size, 32, 32, 8)
        actual = Convolve.convolve_tensor_dataset_2(m, k, bias, strides=(2, 2))

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_8_channel_output_for_3_channel_input_training_set_with_bias_strides_2_no_padding(self):
        """
        Test convolve layers.
        """
        training_set_size = 5

        m = np.ones((training_set_size, 64, 64, 3))  # 3 input channel 64x64 matrix

        k = np.ones((5, 5, 3, 8))  # 3x3 kernel, 3 input, 8 output channels
        bias = np.zeros((8))

        # output = np.zeros((training_set_size, 64, 64, 8))
        expected = (training_set_size, 30, 30, 8)
        actual = Convolve.convolve_tensor_dataset_2(m, k, bias, use_padding=False, strides=(2, 2))

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_tensor_output_8_back(self):
        """
        Test convolve layers.
        """
        m = np.ones((64, 64, 8))  # 3 layer 2x2 matrix
        k = np.ones((5, 5, 3, 8))  # 5x5 kernel with 3 channels, 8 output channels
        expected_output_shape = np.zeros((64, 64, 3)).shape

        actual = Convolve.convolve_tensor_multi_channel_back(m, k)

        # check shape
        self.assertTrue(actual.shape == expected_output_shape, "Unexpected shape")


    def test_convolve_training_set_back(self):
        """
        Test convolve layers.
        """
        training_set_size = 16

        m = np.ones((training_set_size, 64, 64, 8))  # 1 layer matrix
        k = np.ones((7, 7, 3, 8))  # 3x3 kernel with 3 channels, 5 output channels
        output = np.zeros((training_set_size, 64, 64, 3))
        expected = output.shape
        num_output_channels = k.shape[3]

        actual = Convolve.convolve_tensor_dataset_back(m, k)

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_two_datasets(self):
        """
        Test convolve datasets
        """
        training_set_size = 9

        a_prev = np.ones((training_set_size, 18, 18, 3))
        lz = np.ones((training_set_size, 16, 16, 8))
        expected = (training_set_size, 3, 3, 3, 8)

        actual = Convolve.convolve_two_datasets(a_prev, lz, use_padding=False)

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))

    def test_convolve_two_datasets_and_calc_mean(self):
        """
        Test convolve datasets
        """
        training_set_size = 9

        a_prev = np.ones((training_set_size, 18, 18, 3))
        lz = np.ones((training_set_size, 16, 16, 8))
        expected = (3, 3, 3, 8)

        actual = Convolve.convolve_two_datasets_calc_mean(a_prev, lz, use_padding=False)

        actual = actual.shape
        result = (actual == expected)
        self.assertTrue(result, "actual does not match expected. \nActual:\n%s, \nExpected:\n%s" % (actual, expected))
def main():
    """Invoke test function"""

    unittest.main()


if __name__ == "__main__":
    main()
